export const counterCurrencyNameTable = {
  btc: "Bitcoin",
  eth: "Ethereum",
  ltc: "Litecoin",
  bch: "Bitcoin Cash",
  bnb: "Binance Coin",
  eos: "EOS",
  xrp: "Ripple",
  xlm: "Stellar",
  link: "Chainlink",
  dot: "Polkadot",
  yfi: "yearn.finance",
  usd: "US Dollar",
  aed: "United Arab Emirates dirham",
  ars: "Argentine peso",
  aud: "Australian dollar",
  bdt: "Bangladeshi taka",
  bhd: "Bahraini dinar",
  bmd: "Bermudian dollar",
  brl: "Brazilian real",
  cad: "Canadian dollar",
  chf: "Swiss franc",
  clp: "Chilean peso",
  cny: "Renminbi",
  czk: "Czech koruna",
  dkk: "Danish krone",
  eur: "Euro",
  gbp: "Pound sterling",
  hkd: "Hong Kong dollar",
  huf: "Hungarian forint",
  idr: "Indonesian rupiah",
  ils: "Israeli new shekel",
  inr: "Indian rupee",
  jpy: "Japanese yen",
  krw: "South Korean won",
  kwd: "Kuwaiti dinar",
  lkr: "Sri Lankan rupee",
  mmk: "Myanmar kyat",
  mxn: "Mexican peso",
  myr: "Malaysian ringgit",
  ngn: "Nigerian naira",
  nok: "Norwegian krone",
  nzd: "New Zealand dollar",
  php: "Philippine peso",
  pkr: "Pakistani rupee",
  pln: "Polish złoty",
  rub: "Russian ruble",
  sar: "Saudi riyal",
  sek: "Swedish krona",
  sgd: "Singapore dollar",
  thb: "Thai baht",
  try: "Turkish Lira",
  twd: "New Taiwan dollar",
  uah: "Ukrainian Hryvnia",
  vef: "Venezuelan bolívar",
  vnd: "Vietnamese dong",
  zar: "South African rand",
  xdr: "Special Drawing Rights",
  xag: "Silver",
  xau: "Gold",
  bits: "Bitstar",
  sats: "Satoshis",
};
