name: prepare comment body
description: prepare comment for reporting
author: valpinkman
outputs:
  bodySlack:
    description: message formatted body for slack
  bodySlackAuthor:
    description: message formatted body for slack author
  slackAuthor:
    description: slack handle of the author
inputs:
  sha:
    description: prNumber
    required: true
  images:
    description: stringified array of images to include in body of comment
    required: true
  fullrepo:
    description: full repo name
    required: true
  runId:
    description: runId
    required: true
  from:
    description: from
    required: true
  to:
    description: to
    required: true
  pullId:
    description: pullId
    required: true
  author:
    description: author
    required: true
  imgChanged:
    description: imgChanged
    required: true
  testoutput:
    description: testoutput
    required: true
  lintoutput:
    description: lintoutput
    required: true
  jestoutput:
    description: jestoutput
    required: true
runs:
  using: node12
  main: index.js

branding:
  icon: align-center
  color: white
