name: 'run-headless'
description: 'run script in a headless able container'
author: IAmMorrow
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.should-update-screenshots }}
inputs:
  should-update-screenshots:
    description: 'should we update the screenshots ? ()'
    required: false
    default: '0'
branding:
  icon: monitor
  color: blue
