export const SET_MARKET_PARAMS = "SET_MARKET_PARAMS";
export const SET_MARKET_RANGE = "SET_MARKET_RANGE";
export const SET_MARKET_FILTERS = "SET_MARKET_FILTERS";
export const SET_MARKET_LOADING = "SET_MARKET_LOADING";
export const GET_COUNTER_CURRENCIES = "GET_COUNTER_CURRENCIES";
export const GET_MARKET_CRYPTO_CURRENCIES = "GET_MARKET_CRYPTO_CURRENCIES";
export const CONNECTION_ERROR = "CONNECTION_ERROR";
export const RELOAD = "RELOAD";
