name: Merge Crowdin PR
on:
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        if: github.event.check_suite.conclusion == "success" && github.event.check_suite.pull_requests != "" && contains(github.event.check_suite.pull_requests[0].head.ref, 'l10n')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.check_suite.pull_requests[0].number }}
        run: |
          gh pr merge $PR -s --admin
