name: windows production build
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag?"
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.tag}}
      - uses: actions/setup-node@main
        with:
          node-version: 14.x
      - uses: actions/setup-python@v1
        with:
          python-version: "2.7.x"
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn --ignore-scripts --frozen-lockfile
      - name: build the app
        run: yarn dist --dir
      - uses: ledgerhq/actions/get-package-infos@v2.0.0
        id: version
      - name: upload windows app
        uses: actions/upload-artifact@v2
        with:
          name: win-unpacked
          path: dist/win-unpacked
